[build]
  base    = "."
  publish = "apps/consumer/.next"
  command = "cd apps/consumer && NEXT_TELEMETRY_DISABLED=1 npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  included_files = [
    "node_modules/next/**/*",
    "apps/consumer/node_modules/next/**/*"
  ]
  node_bundler = "zisi"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
