[build]
  base    = "."
  publish = ".next"
  command = "cd apps/marketing && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  pinned_version = "5.11.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
